site_name: TTRPG ig lmao
site_url: https://probablyily.github.io/UnnamedTTRPG/
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.indexes
    - toc.follow
    #- navigation.path
plugins:
  - search
  - roamlinks