site_name: TTRPG ig lmao
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.indexes
    - toc.follow
    #- navigation.path
plugins:
  - search
  - roamlinks
